# -*- coding: utf-8 -*-
"""VideoTrimmer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNhof5T0h4ji61nWQs1EqMoq6gOf1lrh
"""

from google.colab import drive
import os
import cv2
import csv

drive.mount('/content/drive', force_remount=True)

origin_dir = 'drive/MyDrive/CS231A/Project/ASLLVD/videos'
target_dir = 'drive/MyDrive/CS231A/Project/ASLLVD/videos_trimmed'
csv_dir = 'drive/MyDrive/CS231A/Project/asllvd_signs_2022_11_29.csv'
# column numbers of relavent info in the csv
name_index = 12 
start_index = 6
end_index = 7
unvalid_count = 0

with open(csv_dir) as csv_file:
  csv_reader = csv.reader(csv_file, delimiter=',')
  line_count = 0
  for row in csv_reader:
    if line_count != 0:
      # get wanted info from csv
      video_name = origin_dir + '/' + row[name_index]
      start_frame = int(row[start_index])
      end_frame = int(row[end_index])
      output_name = target_dir + '/' + str(line_count) + '.mp4'

      cam = cv2.VideoCapture(video_name) # this is the video
      # get properties for writing video
      fps = int(cam.get(cv2.CAP_PROP_FPS))
      frame_size = (int(cam.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cam.get(cv2.CAP_PROP_FRAME_HEIGHT)))
      fourcc = int(cam.get(cv2.CAP_PROP_FOURCC))
      # read from the desired starting frame
      cam.set(cv2.CAP_PROP_POS_FRAMES, start_frame - 1)
      num_wanted_frames = end_frame - start_frame + 1
      frame_count = 0
      output = cv2.VideoWriter(output_name, fourcc, fps, frame_size)
      while frame_count < num_wanted_frames:
        ret, frame = cam.read()
        if not ret:
          unvalid_count += 1
          print('Desired frame number is exceeds the video length')
          break
        frame_count += 1
        output.write(frame)

      cam.release()
      output.release()
      cv2.destroyAllWindows()
    
    line_count += 1

    print(f'Processed {line_count} lines.')
print(f'{unvalid_count} unvalid videos.')